# Generated by Django 4.1.3 on 2023-11-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_project_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
