# Generated by Django 4.1.3 on 2023-11-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_work_alter_techstack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='icon',
            field=models.ImageField(default='Screenshot_2023-11-22_224940.png', upload_to='work_icons/'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.ImageField(upload_to='techstack_icons/'),
        ),
    ]
