# Generated by Django 4.1.3 on 2023-11-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_work_icon_alter_techstack_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='icon',
            new_name='image',
        ),
    ]
