# Generated by Django 4.2.7 on 2024-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_work_tech_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AlterField(
            model_name='techstack',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
