# Generated by Django 4.2.7 on 2024-05-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_experience_delete_work_alter_techstack_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.CharField(default='Owned the development of multiple API endpoints, utilizing Postman for efficient creation and testing. This ensured robust functionality and seamless integration within the system.', max_length=1000),
            preserve_default=False,
        ),
    ]
