# Generated by Django 4.2.7 on 2024-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_end_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='tech1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='tech6',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
    ]
