# Generated by Django 4.2.7 on 2024-05-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_experience_tech1_experience_tech2_experience_tech3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tech2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tech3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tech4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tech5',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tech6',
        ),
        migrations.AlterField(
            model_name='experience',
            name='tech1',
            field=models.CharField(max_length=20),
        ),
    ]
