# Generated by Django 4.2.7 on 2024-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='tech1',
            field=models.CharField(max_length=40),
        ),
    ]
