# Generated by Django 5.0.6 on 2024-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_link',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
