# Generated by Django 5.0.6 on 2024-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_project_github_link_alter_project_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='techstack',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media\\icons'),
        ),
    ]
