# Generated by Django 5.0.6 on 2024-05-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_techstack_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techstack',
            name='icon',
        ),
    ]
